- name: Mysql configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.vasavi.online
  tasks:
  - name: install MySQL 
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql mysql-server
    ansible.builtin.service: 
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      ignore_errors: true
      register: mysql_info


